<template>
    <nav class="bg-white shadow dark:bg-gray-800">
        <div class="container px-6 py-4 mx-auto md:flex md:justify-between md:items-center">
            <div class="flex items-center justify-between">
                <div>
                    <a class="text-2xl font-bold text-gray-800 transition-colors duration-200 transform dark:text-white lg:text-3xl hover:text-gray-700 dark:hover:text-gray-300" href="#"><span style="color: #b4ec50">Green Iraq AI</span>
<!--                        <img src="../../../img/green-iraq-ai-logo.png" width="96" height="59" alt="Green Iraq AI Logo">-->
                    </a>
                </div>
            </div>

        </div>
    </nav>

    <div class="relative flex flex-col-reverse py-16 lg:pt-0 lg:flex-col lg:pb-0">
        <div class="inset-y-0 top-0 right-0 z-0 w-full max-w-xl px-4 mx-auto md:px-0 lg:pr-0 lg:mb-0 lg:mx-0 lg:w-7/12 lg:max-w-full lg:absolute xl:px-0">
            <svg class="absolute left-0 hidden h-full text-white transform -translate-x-1/2 lg:block" viewBox="0 0 100 100" fill="currentColor" preserveAspectRatio="none slice">
                <path d="M50 0H100L50 100H0L50 0Z"></path>
            </svg>
            <img
                class="object-cover w-full h-56 rounded shadow-lg lg:rounded-none lg:shadow-none md:h-96 lg:h-full"
                src="../../../img/hero-image.jpeg"
                alt="license: Thaier_Al-Sudani-Reuters"
            />
        </div>
        <div class="relative flex flex-col items-start w-full max-w-xl px-4 mx-auto md:px-0 lg:px-8 lg:max-w-screen-xl">
            <div class="mb-16 lg:my-40 lg:max-w-lg lg:pr-5">
                <h2 class="mb-5 font-sans text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl sm:leading-none">
                    Think Smarter<br class="hidden md:block" />
                    The Earth needs you
                </h2>
                <p class="pr-5 mb-5 text-base text-gray-700 md:text-lg">
                    Fighting climate change ideas in Iraq based on artificial intelligence.
                </p>
                <span>By: <u><b><a href="https://www.tahseenalaa.com" target="_blank">Tahseen Alaa</a></b></u></span>
            </div>
        </div>
    </div>

    <div class="flex justify-center text-center px-2">
        <p class="py-12 font-bold sm:text-md sm:max-w-sm md:text-xl md:max-w-md lg:text-2xl lg:max-w-3xl">Ideas on this website generated by Artificial Intelligence %100, without human involvement, Powered by OpenAPI GPT-3 which is the most capable deep learning model.</p>
    </div>
    <hr>
</template>

<script>
export default {
    name: "Navbar",
}
</script>

<style scoped>

</style>
